/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactMessage {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface GalleryImage {
  'id' : bigint,
  'url' : string,
  'order' : bigint,
  'caption' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addImage' : ActorMethod<[string, string], bigint>,
  'editImage' : ActorMethod<[bigint, string, string], undefined>,
  'getAboutImage' : ActorMethod<[], [] | [string]>,
  'getAllImages' : ActorMethod<[], Array<GalleryImage>>,
  'getAllMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllMessagesByName' : ActorMethod<[string], Array<ContactMessage>>,
  'getMessageById' : ActorMethod<[bigint], ContactMessage>,
  'removeImage' : ActorMethod<[bigint], undefined>,
  'setAboutImage' : ActorMethod<[string], undefined>,
  'submitMessage' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];