/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GalleryImage = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'order' : IDL.Nat,
  'caption' : IDL.Text,
});
export const Time = IDL.Int;
export const ContactMessage = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'addImage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'editImage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'getAboutImage' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getAllImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getAllMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllMessagesByName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ContactMessage)],
      ['query'],
    ),
  'getMessageById' : IDL.Func([IDL.Nat], [ContactMessage], ['query']),
  'removeImage' : IDL.Func([IDL.Nat], [], []),
  'setAboutImage' : IDL.Func([IDL.Text], [], []),
  'submitMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GalleryImage = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'order' : IDL.Nat,
    'caption' : IDL.Text,
  });
  const Time = IDL.Int;
  const ContactMessage = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'addImage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'editImage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'getAboutImage' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getAllImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getAllMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'getAllMessagesByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getMessageById' : IDL.Func([IDL.Nat], [ContactMessage], ['query']),
    'removeImage' : IDL.Func([IDL.Nat], [], []),
    'setAboutImage' : IDL.Func([IDL.Text], [], []),
    'submitMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };